In [1]:
import torch
import numpy as np

np.set_printoptions(precision=3)

a= [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [4]:
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

rand_tensor.shape

torch.transpose(rand_tensor, )

tensor([[0.2333, 0.2344, 0.4365],
        [0.4112, 0.3182, 0.7273]])


torch.Size([2, 3])

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.1805, 0.8580, 0.7009],
        [0.3107, 0.5263, 0.0666]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
tensor = torch.ones(2, 3)

t1 = torch.cat([tensor, tensor])
print(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
